---
namePrefix: cost-attribution

createNamespace: true
namespace: kubernetes-cost-attribution

enableRBAC: true
enableRBACGoogleMarketPlace: false

reportingSecret: test-secret

prometheus:
  image:
    repository: prom/prometheus
    tag: "v2.2.1"
    pullPolicy: Always
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 200m
      memory: 200Mi
  disk:
    size: 50Gi
  dataRetention: 60d

grafana:
  image:
    repository: grafana/grafana
    tag: "5.1.2"
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 20Mi
  credentials:
    user: admin
    password: kube-cost-attribution
  enableLoadbalancer: true
  ingress:
    enable: false
    ingressClass: nginx
    enableTlsAcme: true
    hostname: kca.demo.devops.bot
    annotations:
      enable: false
      whitelistSourceRange: "1.1.1.1/32,2.2.2.2/32"

mkAgent:
  image:
    repository: gcr.io/managedkube/kubernetes-cost-attribution/agent
    tag: "1.0"
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 20Mi
  ubbAgent:
    enable: false
    image:
      # source: gcr.io/cloud-marketplace-tools/metering/ubbagent:latest
      repository: gcr.io/managedkube/kubernetes-cost-attribution/ubbagent
      tag: "1.0"
      pullPolicy: Always
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 25Mi
