---
namePrefix: cost-attribution

enableGCEBillingAgent: true

createNamespace: true
namespace: kubernetes-cost-attribution

enableRBAC: false
enableRBACGoogleMarketPlace: false

reportingSecret: test-secret

billing:
  image:
    repository: gcr.io/managedkube/kubernetes-cost-attribution
    tag: "1.0"
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 250m
      memory: 250Mi
  ubbAgent:
    enable: true
    image:
      repository: gcr.io/managedkube/kubernetes-cost-attribution/ubbagent
      tag: "1.0"
      pullPolicy: Always
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 25Mi
prometheus:
  image:
    repository: prom/prometheus
    tag: "v2.2.1"
    pullPolicy: Always
  resources:
    limits:
      cpu: 4000m
      memory: 4000Mi
    requests:
      cpu: 250m
      memory: 250Mi
  disk:
    size: 50Gi
  dataRetention: 60d

kubeStateMetrics:
  image:
    repository: k8s.gcr.io/kube-state-metrics
    tag: "v1.3.1"
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 20Mi

grafana:
  image:
    repository: grafana/grafana
    tag: "5.1.2"
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 20Mi
  credentials:
    user: admin
    password: kube-cost-attribution
  enableLoadbalancer: true
  ingress:
    enable: false
    ingressClass: nginx
    enableTlsAcme: true
    hostname: kca.demo.devops.bot
    annotations:
      enable: false
      whitelistSourceRange: "1.1.1.1/32,2.2.2.2/32"

mkAgent:
  image:
    repository: gcr.io/managedkube/kubernetes-cost-attribution/agent
    tag: "0.1"
    pullPolicy: Always
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 20m
      memory: 20Mi
